### ISSUE TITLE
Add XKCD title and hover text to slack message

### ISSUE THREAD

**Issue by duskmoss** [raysarebest/xkcd-slack#1]
If your bot could add the title of the strip, and the text that would be really useful. Could probably format it more like how slack auto parses it from the link. I've attached an example. 

![xkcdslack](https://cloud.githubusercontent.com/assets/1187110/14722694/055c365e-07ca-11e6-8992-c139c43196db.png)

**Comment by raysarebest** [comment]
I like this idea. This is now what happens when you request a comic

**Comment by duskmoss** [comment]
Awesome :)
