### ISSUE TITLE
Beepboop reports no bot

### ISSUE THREAD

**Issue by ingeniousclown** [raysarebest/xkcd-slack#2]
Beepboop tries to add a bot but says that your app does not have a bot associated with it.

**Comment by raysarebest** [comment]
I'm aware of this, and I plan on getting support for it in the morning, when I have time. I'll post updates on this issue accordingly

**Comment by raysarebest** [comment]
I finally stopped being lazy and  migrated this over to my personal server, so it's up and running again, and should be permanently 🎉

**Comment by raysarebest** [comment]
You'll have to hit the "Add to Slack" button again, though, but it should work
